export const projects = [
  {
    id: "super-agent-party",
    name: "Super Agent Party",
    kind: "main",
    parent: null,
    category: { zh: "AI 伙伴", en: "AI COMPANION" },
    summary: {
      zh: "给 AI 一个声音、眼睛和身体。",
      en: "Give AI a voice, eyes, and a body.",
    },
    description: {
      zh: "一个可以自托管的全能 AI 伴侣。它把大模型、语音、视觉、Live2D / VRM 虚拟形象与 MCP 工具连接起来，让智能体能聊天、直播、玩游戏，也能照看智能家居。",
      en: "A self-hosted AI companion that brings language models, speech, vision, Live2D / VRM avatars and MCP tools together. It can chat, stream, play games and help run your smart home.",
    },
    tags: ["MCP", "Live2D / VRM", "ComfyUI"],
    stars: 2712,
    language: "JavaScript",
    license: "AGPL-3.0",
    source: "https://github.com/heshengtao/super-agent-party",
    demo: "https://www.agentparty.top",
  },
  {
    id: "comfyui-llm-party",
    name: "ComfyUI LLM Party",
    kind: "main",
    parent: null,
    category: { zh: "智能体工作流", en: "AGENT WORKFLOWS" },
    summary: {
      zh: "在节点画布中搭建完整 AI 应用。",
      en: "Build complete AI apps on a node canvas.",
    },
    description: {
      zh: "把 LLM 智能体、语音、OCR、图像生成与知识检索带进 ComfyUI。拖动节点，就能把模型、工具和多模态能力连接成自己的工作流。",
      en: "Bring LLM agents, speech, OCR, image generation and retrieval into ComfyUI. Connect models, tools and multimodal capabilities into your own workflows by arranging nodes.",
    },
    tags: ["ComfyUI", "MCP", "GraphRAG"],
    stars: 2370,
    language: "Python",
    license: "AGPL-3.0",
    source: "https://github.com/heshengtao/comfyui_LLM_party",
    demo: null,
  },
  {
    id: "exameow",
    name: "Exameow",
    kind: "main",
    parent: null,
    category: { zh: "学习工具", en: "LEARNING TOOL" },
    summary: {
      zh: "上传资料，几秒生成一整套试卷。",
      en: "Turn study notes into a full exam in seconds.",
    },
    description: {
      zh: "端侧优先的 AI 出题工具。导入课件或教材，自动生成五类题型，并在练习模式和错题本里持续复习。桌面、云端与自托管版本共用同一套界面。",
      en: "A local-first AI exam generator. Import courseware or textbooks, create five question types, and keep learning with practice mode and a mistake tracker. One interface spans desktop, cloud and self-hosted editions.",
    },
    tags: ["Tauri", "Vue 3", "Education"],
    stars: 55,
    language: "TypeScript · Rust",
    license: "Apache-2.0",
    source: "https://github.com/heshengtao/exameow",
    demo: "https://exam.superagentparty.com/",
  },
  {
    id: "labelall",
    name: "LabelAll",
    kind: "main",
    parent: null,
    category: { zh: "数据标注", en: "DATA ANNOTATION" },
    summary: {
      zh: "打开文件夹，直接开始标注。",
      en: "Open a folder and start annotating.",
    },
    description: {
      zh: "免费的图像数据集查看与标注工具。无需格式转换或建立工程，就能直接读取 COCO、YOLO、Pascal VOC 和 ImageFolder，并以原格式导出。",
      en: "A free tool for viewing and annotating image datasets. Read COCO, YOLO, Pascal VOC and ImageFolder directly, without conversion or project setup, then export in the original format.",
    },
    tags: ["COCO", "YOLO", "Docker"],
    stars: 1,
    language: "TypeScript",
    license: "Apache-2.0",
    source: "https://github.com/heshengtao/labelall",
    demo: "https://labelall.superagentparty.com/",
  },
  {
    id: "sap-live2d",
    name: "sap-live2d",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "虚拟形象", en: "AVATAR" },
    summary: {
      zh: "为智能体接入 Live2D 形象。",
      en: "Bring Live2D avatars to the party.",
    },
    tags: ["Live2D"],
    stars: 8,
    source: "https://github.com/heshengtao/sap-live2d",
  },
  {
    id: "sap-story-adventure",
    name: "sap-story-adventure",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "互动故事", en: "INTERACTIVE STORY" },
    summary: {
      zh: "由 AI 驱动的互动故事冒险。",
      en: "An AI-powered interactive story adventure.",
    },
    tags: ["Story"],
    stars: 4,
    source: "https://github.com/heshengtao/sap-story-adventure",
  },
  {
    id: "sap-web-preview",
    name: "sap-web-preview",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "网页预览", en: "WEB PREVIEW" },
    summary: {
      zh: "在应用中直接预览网页。",
      en: "Preview web pages inside the app.",
    },
    tags: ["Web"],
    stars: 4,
    source: "https://github.com/heshengtao/sap-web-preview",
  },
  {
    id: "desktop-for-sap",
    name: "desktop-for-sap",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "桌面工具", en: "DESKTOP TOOL" },
    summary: {
      zh: "把 Docker 版带到桌面。",
      en: "Bring the Docker edition to desktop.",
    },
    tags: ["Desktop"],
    stars: 3,
    source: "https://github.com/heshengtao/desktop-for-sap",
  },
  {
    id: "sap-aigalgame",
    name: "sap-aigalgame",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "游戏扩展", en: "GAME EXTENSION" },
    summary: {
      zh: "让 AI 角色走进 Galgame。",
      en: "Bring AI characters into a visual novel.",
    },
    tags: ["Game"],
    stars: 3,
    source: "https://github.com/heshengtao/sap-aigalgame",
  },
  {
    id: "sap-example",
    name: "sap-example",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "插件示例", en: "PLUGIN EXAMPLE" },
    summary: {
      zh: "从这里开始创建自己的插件。",
      en: "Start building your own extension here.",
    },
    tags: ["Plugin"],
    stars: 3,
    source: "https://github.com/heshengtao/sap-example",
  },
  {
    id: "sap-aieditor",
    name: "sap-aieditor",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "创作扩展", en: "CREATIVE TOOL" },
    summary: {
      zh: "智能体的 AI 编辑器。",
      en: "An AI editor for the companion.",
    },
    tags: ["Editor"],
    stars: 2,
    source: "https://github.com/heshengtao/sap-aieditor",
  },
  {
    id: "sap-remote",
    name: "sap-remote",
    kind: "satellite",
    parent: "super-agent-party",
    category: { zh: "远程连接", en: "REMOTE ACCESS" },
    summary: {
      zh: "一键把服务连接到公网。",
      en: "Take your service online in one step.",
    },
    tags: ["Remote"],
    stars: 2,
    source: "https://github.com/heshengtao/sap-remote",
  },
  {
    id: "let-llm-party",
    name: "Let-LLM-party",
    kind: "satellite",
    parent: "comfyui-llm-party",
    category: { zh: "学习指南", en: "LEARNING GUIDE" },
    summary: {
      zh: "30 天学会 ComfyUI LLM Party。",
      en: "Learn ComfyUI LLM Party in 30 days.",
    },
    tags: ["Guide"],
    stars: 41,
    source: "https://github.com/heshengtao/Let-LLM-party",
  },
  {
    id: "comfyui-llm-mafia",
    name: "comfyui_LLM_mafia",
    kind: "satellite",
    parent: "comfyui-llm-party",
    category: { zh: "主题扩展", en: "THEME EXTENSION" },
    summary: {
      zh: "ComfyUI LLM Party 黑夜版。",
      en: "The Dark Night edition of LLM Party.",
    },
    tags: ["Theme"],
    stars: 9,
    source: "https://github.com/heshengtao/comfyui_LLM_mafia",
  },
  {
    id: "comfyui-llm-schools",
    name: "comfyui_LLM_schools",
    kind: "satellite",
    parent: "comfyui-llm-party",
    category: { zh: "模型训练", en: "MODEL TRAINING" },
    summary: {
      zh: "用节点工作流微调大模型。",
      en: "Fine-tune LLMs with ComfyUI nodes.",
    },
    tags: ["Fine-tuning"],
    stars: 7,
    source: "https://github.com/heshengtao/comfyui_LLM_schools",
  },
];

const byId = new Map(projects.map((project) => [project.id, project]));

export function getProject(id) {
  return byId.get(id);
}

export function getChildren(parentId) {
  return projects.filter((project) => project.parent === parentId);
}
